"""Add master debug log

Revision ID: 03152cfc0c40
Revises: 787bf4b3547f
Create Date: 2026-07-19 13:08:35.602383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03152cfc0c40'
down_revision: Union[str, Sequence[str], None] = '787bf4b3547f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_pdfs', sa.Column('master_debug_log', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_pdfs', 'master_debug_log')
    # ### end Alembic commands ###
