"""Initial migration

Revision ID: 4cd7fd333dd1
Revises: 
Create Date: 2026-07-19 09:59:38.218595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd7fd333dd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_class_name'), 'classes', ['class_name'], unique=False)
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_normalized_name'), 'faculty', ['normalized_name'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_subject_code'), 'subjects', ['subject_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('uploaded_pdfs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_pdfs_user_id'), 'uploaded_pdfs', ['user_id'], unique=False)
    op.create_table('preview_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('subject_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_name', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_pdfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preview_data_upload_id'), 'preview_data', ['upload_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploaded_pdfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_class_id'), 'timetable_entries', ['class_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_subject_id'), 'timetable_entries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_upload_id'), 'timetable_entries', ['upload_id'], unique=False)
    op.create_table('faculty_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['timetable_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_mappings_entry_id'), 'faculty_mappings', ['entry_id'], unique=False)
    op.create_index(op.f('ix_faculty_mappings_faculty_id'), 'faculty_mappings', ['faculty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_mappings_faculty_id'), table_name='faculty_mappings')
    op.drop_index(op.f('ix_faculty_mappings_entry_id'), table_name='faculty_mappings')
    op.drop_table('faculty_mappings')
    op.drop_index(op.f('ix_timetable_entries_upload_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_subject_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_class_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_preview_data_upload_id'), table_name='preview_data')
    op.drop_table('preview_data')
    op.drop_index(op.f('ix_uploaded_pdfs_user_id'), table_name='uploaded_pdfs')
    op.drop_table('uploaded_pdfs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_subject_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_faculty_normalized_name'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_classes_class_name'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
