"""Add summary stats to UploadedPDF

Revision ID: 645bc482371d
Revises: b679064f817f
Create Date: 2026-07-19 14:02:48.670881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645bc482371d'
down_revision: Union[str, Sequence[str], None] = 'b679064f817f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_pdfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saved_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('warning_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_pdfs', schema=None) as batch_op:
        batch_op.drop_column('error_count')
        batch_op.drop_column('warning_count')
        batch_op.drop_column('saved_count')
        batch_op.drop_column('extracted_count')

    # ### end Alembic commands ###
