"""Add progress tracking to UploadedPDF

Revision ID: 787bf4b3547f
Revises: 8b6a531a8b9d
Create Date: 2026-07-19 11:14:27.737271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787bf4b3547f'
down_revision: Union[str, Sequence[str], None] = '8b6a531a8b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_pdfs', sa.Column('processing_stage', sa.String(length=100), nullable=True))
    op.add_column('uploaded_pdfs', sa.Column('processing_progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_pdfs', 'processing_progress')
    op.drop_column('uploaded_pdfs', 'processing_stage')
    # ### end Alembic commands ###
