"""Isolate per upload_id

Revision ID: b679064f817f
Revises: 03152cfc0c40
Create Date: 2026-07-19 13:24:30.631880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b679064f817f'
down_revision: Union[str, Sequence[str], None] = '03152cfc0c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_classes_class_name')
        batch_op.create_index(batch_op.f('ix_classes_upload_id'), ['upload_id'], unique=False)
        batch_op.create_unique_constraint('uix_upload_class_name', ['upload_id', 'class_name'])
        batch_op.create_foreign_key(batch_op.f('fk_classes_upload_id_uploaded_pdfs'), 'uploaded_pdfs', ['upload_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_faculty_normalized_name')
        batch_op.create_index(batch_op.f('ix_faculty_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_upload_id'), ['upload_id'], unique=False)
        batch_op.create_unique_constraint('uix_upload_normalized_name', ['upload_id', 'normalized_name'])
        batch_op.create_foreign_key(batch_op.f('fk_faculty_upload_id_uploaded_pdfs'), 'uploaded_pdfs', ['upload_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_id', sa.Integer(), nullable=False))
        batch_op.drop_index('ix_subjects_subject_code')
        batch_op.create_index(batch_op.f('ix_subjects_upload_id'), ['upload_id'], unique=False)
        batch_op.create_unique_constraint('uix_upload_subject_code', ['upload_id', 'subject_code'])
        batch_op.create_foreign_key(batch_op.f('fk_subjects_upload_id_uploaded_pdfs'), 'uploaded_pdfs', ['upload_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subjects_upload_id_uploaded_pdfs'), type_='foreignkey')
        batch_op.drop_constraint('uix_upload_subject_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_subjects_upload_id'))
        batch_op.create_index('ix_subjects_subject_code', ['subject_code'], unique=False)
        batch_op.drop_column('upload_id')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_faculty_upload_id_uploaded_pdfs'), type_='foreignkey')
        batch_op.drop_constraint('uix_upload_normalized_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_faculty_upload_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_normalized_name'))
        batch_op.create_index('ix_faculty_normalized_name', ['normalized_name'], unique=1)
        batch_op.drop_column('upload_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classes_upload_id_uploaded_pdfs'), type_='foreignkey')
        batch_op.drop_constraint('uix_upload_class_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_classes_upload_id'))
        batch_op.create_index('ix_classes_class_name', ['class_name'], unique=False)
        batch_op.drop_column('upload_id')

    # ### end Alembic commands ###
